---
- hosts: servers
  tasks:
  - name: Download elasticsearch rpm distr
      get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.3.rpm
      dest: /opt/elasticsearch/
