---
- hosts: servers
  tasks:
  - name: Update System
    raw: yum update
    register: update_result
  - name: Print result
    debug:
      var: update_result.stdout_lines
  - name: Fetch Java version
    shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'                                                                                                                                   
    changed_when: False
    register: java_result
  - debug:
      msg: "{{ java_result.stdout }}"
  - name: Install Java
    yum:
      name: java-1.8.0-openjdk-devel
      state: present
  - name: Install Wget
    yum:
      name: wget
      state: present
  - name: Stop Firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no
      masked: yes
  - name: Disable SElinux
    raw: setenforce 0 && sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config
  - name: Download elasticsearch rpm distr
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.3.rpm
      dest: /opt/elasticsearch/
