---
- hosts: servers
  tasks:
  - name: Update System
    raw: yum update
    register: update_result
  - name: Print result
    debug:
      var: update_result.stdout_lines
  - name: Fetch Java version
    shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'                                                                                                                                   
    changed_when: False
    register: java_result
  - debug:
      msg: "Версия JAVA : {{ java_result.stdout }}"
  - name: Install Java
    when: "'java_result' not in java_result.stdout"
    debug: msg="JAVA не установлена. Будет произведена установка"
    yum:
      name: java-1.8.0-openjdk-devel
      state: present
