---
- hosts: servers
  tasks:
  - name: debug
      debug: msg={{ ansible_distribution }}
  - name: Update System
    raw: yum update
    register: update_result
  - name: Print result
    debug:
      var: update_result.stdout_lines
  - name: Install Java
    yum:
      name: java-1.8.0-openjdk-devel
      state: present
  - name: Fetch Java version
    shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'                                                                                                                                   
    changed_when: False
    register: java_result
  - debug:
      msg: "{{ java_result.stdout }}"
